spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DB_URL:mysql_db:3306}/${DB_NAME:db-spring-boot-mysql}?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
