apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: spring-api
          image: h3rv3/spring-boot-mysql:0.0.1
          imagePullPolicy: Always
          env:
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: mysql-database
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: mysql-user
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: mysql-password
          - name: DB_URL
            value: mysql-service
      imagePullSecrets:
        - name: docker-hub